#include <cxxtest/TestSuite.h>

#include "audio/audiostream.h"
#include "audio/decoders/vorbis.h"

#include "common/array.h"
#include "common/base64.h"
#include "common/memstream.h"
#include "common/str.h"

#if defined(USE_VORBIS) && defined(USE_OGG) && defined(USE_TREMOR)
#define VORBIS_SETUP_CACHE_TESTS

// Ogg Vorbis clips for the setup header cache, made with
//   ffmpeg -f lavfi -i SRC -t T -ar RATE -ac CH -c:a libvorbis -q:a Q
//          -fflags +bitexact -flags:a +bitexact -map_metadata -1 out.ogg
// A1: aevalsrc=0.5*sin(2*PI*440*t)*sin(2*PI*3*t), 0.5 s, 22050 Hz mono, q 2
// A2: aevalsrc=0.4*sin(2*PI*(200+400*t)*t)+0.1*sin(2*PI*2500*t), 0.4 s, 22050 mono, q 2
// A3: anoisesrc=c=pink:a=0.3:s=7, 0.3 s, 22050 mono, q 2
// B:  aevalsrc=0.5*sin(2*PI*330*t)|0.5*sin(2*PI*550*t), 0.3 s, 44100 stereo, q 2
// C:  as A1, 0.3 s, q 7
// A1, A2 and A3 carry the same setup header (3257 bytes); B and C each have
// another one.
static const char *const kVorbis_A1 =
	"T2dnUwACAAAAAAAAAAAAAAAAAAAAAFZkJp4BHgF2b3JiaXMAAAAAASJWAAAAAAAABYoAAAAAAACpAU9nZ1MAAAAAAAAAAAAAAAAA"
	"AAEAAADx7HilDjD////////////////FA3ZvcmJpcwYAAABmZm1wZWcBAAAAFgAAAGVuY29kZXI9TGF2YyBsaWJ2b3JiaXMBBXZv"
	"cmJpcyJCQ1YBAEAAABhCECoFrWOOOsgVIYwZoqBCyinHHULQIaMkQ4g6xjXHGGNHuWSKQsmB0JBVAABAAACkHFdQckkt55xzoxhX"
	"zHHoIOecc+UgZ8xxCSXnnHOOOeeSco4x55xzoxhXDnIpLeecc4EUR4pxpxjnnHOkHEeKcagY55xzbTG3knLOOeecc+Ygh1JyrjXn"
	"nHOkGGcOcgsl55xzxiBnzHHrIOecc4w1t9RyzjnnnHPOOeecc84555xzjDHnnHPOOeecc24x5xZzrjnnnHPOOeccc84555xzIDRk"
	"FQCQAACgoSiK4igOEBqyCgDIAAAQQHEUR5EUS7Ecy9EkDQgNWQUAAAEACAAAoEiGpEiKpViOZmmeJnqiKJqiKquyacqyLMuy67ou"
	"EBqyCgBIAABQURTFcBQHCA1ZBQBkAAAIYCiKoziO5FiSpVmeB4SGrAIAgAAABAAAUAxHsRRN8STP8jzP8zzP8zzP8zzP8zzP8zzP"
	"8zwNCA1ZBQAgAAAAgihkGANCQ1YBAEAAAAghGhlDnVISXAoWQhwRQx1CzkOppYPgKYUlY9JTrEEIIXzvPffee++B0JBVAAAQAABh"
	"FDiIgcckCCGEYhQnRHGmIAghhOUkWMp56CQI3YMQQrice8u59957IDRkFQAACADAIIQQQgghhBBCCCmklFJIKaaYYoopxxxzzDHH"
	"IIMMMuigk046yaSSTjrKJKOOUmsptRRTTLHlFmOttdacc69BKWOMMcYYY4wxxhhjjDHGGCMIDVkFAIAAABAGGWSQQQghhBRSSCmm"
	"mHLMMcccA0JDVgEAgAAAAgAAABxFUiRHciRHkiTJkixJkzzLszzLszxN1ERNFVXVVW3X9m1f9m3f1WXf9mXb1WVdlmXdtW1d1l1d"
	"13Vd13Vd13Vd13Vd13Vd14HQkFUAgAQAgI7kOI7kOI7kSI6kSAoQGrIKAJABABAAgKM4iuNIjuRYjiVZkiZplmd5lqd5mqiJHhAa"
	"sgoAAAQAEAAAAAAAgKIoiqM4jiRZlqZpnqd6oiiaqqqKpqmqqmqapmmapmmapmmapmmapmmapmmapmmapmmapmmapmmapmkCoSGr"
	"AAAJAAAdx3EcR3Ecx3EkR5IkIDRkFQAgAwAgAABDURxFcizHkjRLszzL00TP9FxRNnVTV20gNGQVAAAIACAAAAAAAADHczzHczzJ"
	"kzzLczzHkzxJ0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRNA0JDVgIAZAAAEJOQSk6xV0YpxiS0Xiqk"
	"FJPUe6iYYkw67alCBikHuYdKIaWg094ypZBSDHunmELIGOqhg5AxhbDX2nPPvfceCA1ZEQBEAQAAxiDGEGPIMSYlgxIxxyRkUiLn"
	"nJROSialpFZazKSEmEqLkXNOSiclk1JaC6llkkprJaYCAAACHAAAAiyEQkNWBABRAACIMUgppBRSSjGnmENKKceUY0gp5ZxyTjnH"
	"mHQQKucYdA5KpJRyjjmnnHMSMgeVcw5CJp0AAIAABwCAAAuh0JAVAUCcAACAkHOKMQgRYxBCCSmFUFKqnJPSQUmpg5JSSanFklKM"
	"lXNSOgkpdRJSKinFWFKKLaRUY2kt19JSjS3GnFuMvYaUYi2p1Vpaq7nFWHOLNffIOUqdlNY6Ka2l1mpNrdXaSWktpNZiaS3G1mLN"
	"KcacMymthZZiK6nF2GLLNbWYc2kt1xRjzynGnmusucecgzCt1ZxayznFmHvMseeYcw+Sc5Q6Ka11UlpLrdWaWqs1k9Jaaa3GkFqL"
	"LcacW4sxZ1JaLKnFWFqKMcWYc4st19BarinGnFOLOcdag5Kx9l5aqznFmHuKreeYczA2x547SrmW1nourfVecy5C1tyLaC3n1GoP"
	"Ksaec87B2NyDEK3lnGrsPcXYe+45GNtz8K3W4FvNRcicg9C5+KZ7MEbV2oPMtQiZcxA66CJ08Ml4lGoureVcWus91hp8zTkI0Vru"
	"KcbeU4u9156bsL0HIVrLPcXYg4ox+JpzMDrnYlStwcecg5C1FqF7L0rnIJSqtQeZa1Ay1yJ08MXooIsvAABgwAEAIMCEMlBoyIoA"
	"IE4AgEHIOaUYhEopCKGElEIoKVWMSciYg5IxJ6WUUloIJbWKMQiZY1Iyx6SEEloqJbQSSmmplNJaKKW1llqMKbUWQymphVJaK6W0"
	"llqqMbVWY8SYlMw5KZljUkoprZVSWqsck5IxKKmDkEopKcVSUouVc1Iy6Kh0EEoqqcRUUmmtpNJSKaXFklJsKcVUW4u1hlJaLKnE"
	"VlJqMbVUW4sx14gxKRlzUjLnpJRSUiultJY5J6WDjkrmoKSSUmulpBQz5qR0DkrKIKNSUootpRJTKKW1klJspaTWWoy1ptRaLSW1"
	"VlJqsZQSW4sx1xZLTZ2U1koqMYZSWmsx5ppaizGUElspKcaSSmytxZpbbDmGUlosqcRWSmqx1ZZja7Hm1FKNKbWaW2y5xpRTj7X2"
	"nFqrNbVUY2ux5lhbb7XWnDsprYVSWislxZhai7HFWHMoJbaSUmylpBhbbLm2FmMPobRYSmqxpBJjazHmGFuOqbVaW2y5ptRirbX2"
	"HFtuPaUWa4ux5tJSjTXX3mNNORUAADDgAAAQYEIZKDRkJQAQBQAAGMMYYxAapZxzTkqDlHPOScmcgxBCSplzEEJIKXNOQkotZc5B"
	"SKm1UEpKrcUWSkmptRYLAAAocAAACLBBU2JxgEJDVgIAUQAAiDFKMQahMUYp5yA0xijFGIRKKcack1ApxZhzUDLHnINQSuaccxBK"
	"CSGUUkpKIYRSSkmpAACAAgcAgAAbNCUWByg0ZEUAEAUAABhjnDPOIQqdpc5SJKmj1lFrKKUaS4ydxlZ767nTGnttuTeUSo2p1o5r"
	"y7nV3mlNPbccCwAAO3AAADuwEAoNWQkA5AEAEMYoxZhzzhmFGHPOOecMUow555xzijHnnIMQQsWYc85BCCFzzjkIoYSSOecchBBK"
	"6JyDUEoppXTOQQihlFI65yCEUkopnXMQSimllAIAgAocAAACbBTZnGAkqNCQlQBAHgAAYAxCzklprWHMOQgt1dgwxhyUlGKLnIOQ"
	"Uou5RsxBSCnGoDsoKbUYbPCdhJRaizkHk1KLNefeg0iptZqDzj3VVnPPvfecYqw1595zLwAAd8EBAOzARpHNCUaCCg1ZCQDkAQAQ"
	"CCnFmHPOGaUYc8w554xSjDHmnHOKMcacc85BxRhjzjkHIWPMOecghJAx5pxzEELonHMOQgghdM45ByGEEDrnoIMQQgidcxBCCCGE"
	"AgCAChwAAAJsFNmcYCSo0JCVAEA4AAAAIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQggh"
	"hBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEELonHPOOeec"
	"c84555xzzjnnnHPOOScAyLfCAcD/wcYZVpLOCkeDCw1ZCQCEAwAACkEopWIQSiklkk46KZ2TUEopkYNSSumklFJKCaWUUkoIpZRS"
	"SggdlFJCKaWUUkoppZRSSimllFI6KaWUUkoppZTKOSmlk1JKKaVEzkkpIZRSSimlhFJKKaWUUkoppZRSSimllFJKKaWEEEIIIYQQ"
	"QgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQCALgbHAAgEmycYSXprHA0uNCQlQBASAAAoBRzjkoIKZSQUqiYoo5CKSmkUkoK"
	"EWPOSeochVBSKKmDyjkIpaSUQiohdc5BByWFkFIJIZWOOugolFBSKiWU0jkopYQUSkoplZBCSKl0lFIoJZWUQiohlVJKSCWVEEoK"
	"naRUSgqppFRSCJ10kEInJaSSSgqpk5RSKiWllEpKJXRSQioppRBCSqmUEEpIKaVOUkmppBRCKCGFlFJKJaWSSkohlVRCCaWklFIo"
	"oaRUUkoppZJSKQAA4MABACDACDrJqLIIG0248AAUGrISACADAECUdNZpp0kiCDFFmScNKcYgtaQswxBTkonxFGOMOShGQw4x5JQY"
	"F0oIoYNiPCaVQ8pQUbm31DkFxRZjfO+xFwEAAAgCAASEBAAYICiYAQAGBwgjBwIdAQQObQCAgQiZCQwKocFBJgA8QERIBQCJCYrS"
	"hS4IIYJ0EWTxwIUTN5644YQObRAAAAAAABAA8AEAkFAAERHRzFVYXGBkaGxwdHh8gIQEAAAAAAAIAHwAACQiQERENHMVFhcYGRob"
	"HB0eHyAhAQAAAAAAAAAAQEBAAAAAAAAgAAAAQEBPZ2dTAAQRKwAAAAAAAAAAAAACAAAAcwNfMRcsGhkYGRoXGRkYGBgbFxgaGBkY"
	"GRgZNASflYazLtjPJAAOPUDI1H848kSWlpa2cxpiGkVRFEVRFEVRFEVRFEVRFEUAGstaNjwAiG+AXQUAAAAAAGhTNgBY1VIjAwd+"
	"Kxt2dgWQfAx2FQAAAAAAYDUGAGvsmisAvksbNjICiH+DXQUAAAAAAFAQAPDeD8YCHlybd0oAYEBG2CWAP04NAAAAAEB1+b4GAP5L"
	"m/daAGBAdthVAAAAAACAxmUDgMY4rYgJPitr90QDiCfCLgHsqQIAAAAAAPuaAADeqtpd8pD+EFeEXQL4awMAAAAAADfbeQoA3soa"
	"nkQDKI/DLgH8nKoAAAAAAFgf0j8EAD47K++1CCD5IOwSwL8LAAAAAMDm9wcBAJ5L63YsAIgnwK4CAAAAAAAIDQDU+GtsAP5bG3dK"
	"ABC/HXYJ4I/TAAAAAABUPgcVAB5MW3ZaAGBANthVAAAAAACAxmUDgMYPnC0mAF47a/dEA4gnwC4BvMMLAAAAAADNFQEA/sqa77gC"
	"ECfALgH8tQEAAAAAgG3A+RAAvpraXVIx/UAHdgngb6cqAAAAAAC7Kv1+AAA+K2v3SgCQfAF2CeDfNwAAAAAAuuqtBwC+Sxt2WgQQ"
	"/w67CgAAAAAAEIQGAMmVi2ID3lsbdkYEkPwRdgngP98HAAAAAGA6fBEAHkxbNloEEL8ddhUAAAAAACCHAUDjZX7GBH5La/dEAYhP"
	"gF0CeIcXAAAAAICMlwcAAB7rGu+5BhBXhF0C+GsTAAAAAACsVxzHAAA+CVouKb2cEDRLdgmwp08H2A4AAJDCXM3PybshEuTX0zPx"
	"nTbto/fkJZqc75NJlIi7YykN";
static const uint32 kVorbis_A1_Size = 4068;

static const char *const kVorbis_A2 =
	"T2dnUwACAAAAAAAAAAAAAAAAAAAAAFZkJp4BHgF2b3JiaXMAAAAAASJWAAAAAAAABYoAAAAAAACpAU9nZ1MAAAAAAAAAAAAAAAAA"
	"AAEAAADx7HilDjD////////////////FA3ZvcmJpcwYAAABmZm1wZWcBAAAAFgAAAGVuY29kZXI9TGF2YyBsaWJ2b3JiaXMBBXZv"
	"cmJpcyJCQ1YBAEAAABhCECoFrWOOOsgVIYwZoqBCyinHHULQIaMkQ4g6xjXHGGNHuWSKQsmB0JBVAABAAACkHFdQckkt55xzoxhX"
	"zHHoIOecc+UgZ8xxCSXnnHOOOeeSco4x55xzoxhXDnIpLeecc4EUR4pxpxjnnHOkHEeKcagY55xzbTG3knLOOeecc+Ygh1JyrjXn"
	"nHOkGGcOcgsl55xzxiBnzHHrIOecc4w1t9RyzjnnnHPOOeecc84555xzjDHnnHPOOeecc24x5xZzrjnnnHPOOeccc84555xzIDRk"
	"FQCQAACgoSiK4igOEBqyCgDIAAAQQHEUR5EUS7Ecy9EkDQgNWQUAAAEACAAAoEiGpEiKpViOZmmeJnqiKJqiKquyacqyLMuy67ou"
	"EBqyCgBIAABQURTFcBQHCA1ZBQBkAAAIYCiKoziO5FiSpVmeB4SGrAIAgAAABAAAUAxHsRRN8STP8jzP8zzP8zzP8zzP8zzP8zzP"
	"8zwNCA1ZBQAgAAAAgihkGANCQ1YBAEAAAAghGhlDnVISXAoWQhwRQx1CzkOppYPgKYUlY9JTrEEIIXzvPffee++B0JBVAAAQAABh"
	"FDiIgcckCCGEYhQnRHGmIAghhOUkWMp56CQI3YMQQrice8u59957IDRkFQAACADAIIQQQgghhBBCCCmklFJIKaaYYoopxxxzzDHH"
	"IIMMMuigk046yaSSTjrKJKOOUmsptRRTTLHlFmOttdacc69BKWOMMcYYY4wxxhhjjDHGGCMIDVkFAIAAABAGGWSQQQghhBRSSCmm"
	"mHLMMcccA0JDVgEAgAAAAgAAABxFUiRHciRHkiTJkixJkzzLszzLszxN1ERNFVXVVW3X9m1f9m3f1WXf9mXb1WVdlmXdtW1d1l1d"
	"13Vd13Vd13Vd13Vd13Vd14HQkFUAgAQAgI7kOI7kOI7kSI6kSAoQGrIKAJABABAAgKM4iuNIjuRYjiVZkiZplmd5lqd5mqiJHhAa"
	"sgoAAAQAEAAAAAAAgKIoiqM4jiRZlqZpnqd6oiiaqqqKpqmqqmqapmmapmmapmmapmmapmmapmmapmmapmmapmmapmmapmkCoSGr"
	"AAAJAAAdx3EcR3Ecx3EkR5IkIDRkFQAgAwAgAABDURxFcizHkjRLszzL00TP9FxRNnVTV20gNGQVAAAIACAAAAAAAADHczzHczzJ"
	"kzzLczzHkzxJ0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRNA0JDVgIAZAAAEJOQSk6xV0YpxiS0Xiqk"
	"FJPUe6iYYkw67alCBikHuYdKIaWg094ypZBSDHunmELIGOqhg5AxhbDX2nPPvfceCA1ZEQBEAQAAxiDGEGPIMSYlgxIxxyRkUiLn"
	"nJROSialpFZazKSEmEqLkXNOSiclk1JaC6llkkprJaYCAAACHAAAAiyEQkNWBABRAACIMUgppBRSSjGnmENKKceUY0gp5ZxyTjnH"
	"mHQQKucYdA5KpJRyjjmnnHMSMgeVcw5CJp0AAIAABwCAAAuh0JAVAUCcAACAkHOKMQgRYxBCCSmFUFKqnJPSQUmpg5JSSanFklKM"
	"lXNSOgkpdRJSKinFWFKKLaRUY2kt19JSjS3GnFuMvYaUYi2p1Vpaq7nFWHOLNffIOUqdlNY6Ka2l1mpNrdXaSWktpNZiaS3G1mLN"
	"KcacMymthZZiK6nF2GLLNbWYc2kt1xRjzynGnmusucecgzCt1ZxayznFmHvMseeYcw+Sc5Q6Ka11UlpLrdWaWqs1k9Jaaa3GkFqL"
	"LcacW4sxZ1JaLKnFWFqKMcWYc4st19BarinGnFOLOcdag5Kx9l5aqznFmHuKreeYczA2x547SrmW1nourfVecy5C1tyLaC3n1GoP"
	"Ksaec87B2NyDEK3lnGrsPcXYe+45GNtz8K3W4FvNRcicg9C5+KZ7MEbV2oPMtQiZcxA66CJ08Ml4lGoureVcWus91hp8zTkI0Vru"
	"KcbeU4u9156bsL0HIVrLPcXYg4ox+JpzMDrnYlStwcecg5C1FqF7L0rnIJSqtQeZa1Ay1yJ08MXooIsvAABgwAEAIMCEMlBoyIoA"
	"IE4AgEHIOaUYhEopCKGElEIoKVWMSciYg5IxJ6WUUloIJbWKMQiZY1Iyx6SEEloqJbQSSmmplNJaKKW1llqMKbUWQymphVJaK6W0"
	"llqqMbVWY8SYlMw5KZljUkoprZVSWqsck5IxKKmDkEopKcVSUouVc1Iy6Kh0EEoqqcRUUmmtpNJSKaXFklJsKcVUW4u1hlJaLKnE"
	"VlJqMbVUW4sx14gxKRlzUjLnpJRSUiultJY5J6WDjkrmoKSSUmulpBQz5qR0DkrKIKNSUootpRJTKKW1klJspaTWWoy1ptRaLSW1"
	"VlJqsZQSW4sx1xZLTZ2U1koqMYZSWmsx5ppaizGUElspKcaSSmytxZpbbDmGUlosqcRWSmqx1ZZja7Hm1FKNKbWaW2y5xpRTj7X2"
	"nFqrNbVUY2ux5lhbb7XWnDsprYVSWislxZhai7HFWHMoJbaSUmylpBhbbLm2FmMPobRYSmqxpBJjazHmGFuOqbVaW2y5ptRirbX2"
	"HFtuPaUWa4ux5tJSjTXX3mNNORUAADDgAAAQYEIZKDRkJQAQBQAAGMMYYxAapZxzTkqDlHPOScmcgxBCSplzEEJIKXNOQkotZc5B"
	"SKm1UEpKrcUWSkmptRYLAAAocAAACLBBU2JxgEJDVgIAUQAAiDFKMQahMUYp5yA0xijFGIRKKcack1ApxZhzUDLHnINQSuaccxBK"
	"CSGUUkpKIYRSSkmpAACAAgcAgAAbNCUWByg0ZEUAEAUAABhjnDPOIQqdpc5SJKmj1lFrKKUaS4ydxlZ767nTGnttuTeUSo2p1o5r"
	"y7nV3mlNPbccCwAAO3AAADuwEAoNWQkA5AEAEMYoxZhzzhmFGHPOOecMUow555xzijHnnIMQQsWYc85BCCFzzjkIoYSSOecchBBK"
	"6JyDUEoppXTOQQihlFI65yCEUkopnXMQSimllAIAgAocAAACbBTZnGAkqNCQlQBAHgAAYAxCzklprWHMOQgt1dgwxhyUlGKLnIOQ"
	"Uou5RsxBSCnGoDsoKbUYbPCdhJRaizkHk1KLNefeg0iptZqDzj3VVnPPvfecYqw1595zLwAAd8EBAOzARpHNCUaCCg1ZCQDkAQAQ"
	"CCnFmHPOGaUYc8w554xSjDHmnHOKMcacc85BxRhjzjkHIWPMOecghJAx5pxzEELonHMOQgghdM45ByGEEDrnoIMQQgidcxBCCCGE"
	"AgCAChwAAAJsFNmcYCSo0JCVAEA4AAAAIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQggh"
	"hBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEELonHPOOeec"
	"c84555xzzjnnnHPOOScAyLfCAcD/wcYZVpLOCkeDCw1ZCQCEAwAACkEopWIQSiklkk46KZ2TUEopkYNSSumklFJKCaWUUkoIpZRS"
	"SggdlFJCKaWUUkoppZRSSimllFI6KaWUUkoppZTKOSmlk1JKKaVEzkkpIZRSSimlhFJKKaWUUkoppZRSSimllFJKKaWEEEIIIYQQ"
	"QgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQCALgbHAAgEmycYSXprHA0uNCQlQBASAAAoBRzjkoIKZSQUqiYoo5CKSmkUkoK"
	"EWPOSeochVBSKKmDyjkIpaSUQiohdc5BByWFkFIJIZWOOugolFBSKiWU0jkopYQUSkoplZBCSKl0lFIoJZWUQiohlVJKSCWVEEoK"
	"naRUSgqppFRSCJ10kEInJaSSSgqpk5RSKiWllEpKJXRSQioppRBCSqmUEEpIKaVOUkmppBRCKCGFlFJKJaWSSkohlVRCCaWklFIo"
	"oaRUUkoppZJSKQAA4MABACDACDrJqLIIG0248AAUGrISACADAECUdNZpp0kiCDFFmScNKcYgtaQswxBTkonxFGOMOShGQw4x5JQY"
	"F0oIoYNiPCaVQ8pQUbm31DkFxRZjfO+xFwEAAAgCAASEBAAYICiYAQAGBwgjBwIdAQQObQCAgQiZCQwKocFBJgA8QERIBQCJCYrS"
	"hS4IIYJ0EWTxwIUTN5644YQObRAAAAAAABAA8AEAkFAAERHRzFVYXGBkaGxwdHh8gIQEAAAAAAAIAHwAACQiQERENHMVFhcYGRob"
	"HB0eHyAhAQAAAAAAAAAAQEBAAAAAAAAgAAAAQEBPZ2dTAAR0IgAAAAAAAAAAAAACAAAAOSZ1ERQfJSIgHyEhIyMkIiQlIiMkIx4c"
	"Moyt4xrx4udzBACAAgBAvtNpRM6g6i0tLR0AALD52wHaKzv3WWteX91W64wmdgnZ1AQAcjgAAACcVff7EAAAAMC/uwEA/gs790jz"
	"dYet1jK7hPm7BEAOEgAAgFw/XQYAAACA17QCAP77Ok/IaJsx6LbZJfhPAiAHCQAAACcnrQ4AAAAAvSgAfvx6V4BtwqD7ZpfgfiYB"
	"yEECAACAHdrpBAAAAAAUAP77upwCWXWg+2ZXAQAgBwkAAMAEAAAAjoECgCSOC8YHAP4LO/eArTrQbbNL4M9nAHL4BAAAAKblTa0A"
	"AAAAXhMUAD4su/aAmb+d0lpuYpfAHN4AkMMDAAAA7MH7dwkAAAC8pgIAfiy7rBlm/nZWt93ELgH/6wQghwcAAADwo1TqSAAAAOoq"
	"DABeLFs8b8v07cHQbTexS0D38ADI4QEAAAD07wPjAgAAgLpyAAC+/NpH6WPaoezE7BIw/90MkMMDAAAAYNd/7QMAAEBtkgAAfvza"
	"RE3alCOu3qXZJcDnPwnI4QMAAACA2uTOjgAAANRVqgAAfvzaRIMyHAZk69LsKgAA5CAAAAAgbxsAAAC+wwIASP6cyzMjAP4LG72i"
	"czjiH7s0uwTw50OAHAQAAAAATFfrOAAAABxVAAB+Kyu9jC58e1y9225ilwDaTT2AHAQAAAAAmM5OBQAAAFYBAB4rC16bXfj25MGu"
	"3cQuAez/aQZyEAAAAAAgl+J/FQAAgN4qAPYqI9w41hR4skPjJnYJQDQAOQgAAAAAqDy712MSAAC46hQAXDF9eKwW7S4AANAKAAB5"
	"mwAAAADgx3YB5fVwEwMAVDO+8pfSH+a/DwEAWgEAALv2PBYAAAAAgOtaACwp7njO/w+yAAAABCcMw9r7R8teVwIhAAAAH80I8KMf"
	"AdP4uIz75YUwjY8z1ssLoYwD";
static const uint32 kVorbis_A2_Size = 4143;

static const char *const kVorbis_A3 =
	"T2dnUwACAAAAAAAAAAAAAAAAAAAAAFZkJp4BHgF2b3JiaXMAAAAAASJWAAAAAAAABYoAAAAAAACpAU9nZ1MAAAAAAAAAAAAAAAAA"
	"AAEAAADx7HilDjD////////////////FA3ZvcmJpcwYAAABmZm1wZWcBAAAAFgAAAGVuY29kZXI9TGF2YyBsaWJ2b3JiaXMBBXZv"
	"cmJpcyJCQ1YBAEAAABhCECoFrWOOOsgVIYwZoqBCyinHHULQIaMkQ4g6xjXHGGNHuWSKQsmB0JBVAABAAACkHFdQckkt55xzoxhX"
	"zHHoIOecc+UgZ8xxCSXnnHOOOeeSco4x55xzoxhXDnIpLeecc4EUR4pxpxjnnHOkHEeKcagY55xzbTG3knLOOeecc+Ygh1JyrjXn"
	"nHOkGGcOcgsl55xzxiBnzHHrIOecc4w1t9RyzjnnnHPOOeecc84555xzjDHnnHPOOeecc24x5xZzrjnnnHPOOeccc84555xzIDRk"
	"FQCQAACgoSiK4igOEBqyCgDIAAAQQHEUR5EUS7Ecy9EkDQgNWQUAAAEACAAAoEiGpEiKpViOZmmeJnqiKJqiKquyacqyLMuy67ou"
	"EBqyCgBIAABQURTFcBQHCA1ZBQBkAAAIYCiKoziO5FiSpVmeB4SGrAIAgAAABAAAUAxHsRRN8STP8jzP8zzP8zzP8zzP8zzP8zzP"
	"8zwNCA1ZBQAgAAAAgihkGANCQ1YBAEAAAAghGhlDnVISXAoWQhwRQx1CzkOppYPgKYUlY9JTrEEIIXzvPffee++B0JBVAAAQAABh"
	"FDiIgcckCCGEYhQnRHGmIAghhOUkWMp56CQI3YMQQrice8u59957IDRkFQAACADAIIQQQgghhBBCCCmklFJIKaaYYoopxxxzzDHH"
	"IIMMMuigk046yaSSTjrKJKOOUmsptRRTTLHlFmOttdacc69BKWOMMcYYY4wxxhhjjDHGGCMIDVkFAIAAABAGGWSQQQghhBRSSCmm"
	"mHLMMcccA0JDVgEAgAAAAgAAABxFUiRHciRHkiTJkixJkzzLszzLszxN1ERNFVXVVW3X9m1f9m3f1WXf9mXb1WVdlmXdtW1d1l1d"
	"13Vd13Vd13Vd13Vd13Vd14HQkFUAgAQAgI7kOI7kOI7kSI6kSAoQGrIKAJABABAAgKM4iuNIjuRYjiVZkiZplmd5lqd5mqiJHhAa"
	"sgoAAAQAEAAAAAAAgKIoiqM4jiRZlqZpnqd6oiiaqqqKpqmqqmqapmmapmmapmmapmmapmmapmmapmmapmmapmmapmmapmkCoSGr"
	"AAAJAAAdx3EcR3Ecx3EkR5IkIDRkFQAgAwAgAABDURxFcizHkjRLszzL00TP9FxRNnVTV20gNGQVAAAIACAAAAAAAADHczzHczzJ"
	"kzzLczzHkzxJ0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRNA0JDVgIAZAAAEJOQSk6xV0YpxiS0Xiqk"
	"FJPUe6iYYkw67alCBikHuYdKIaWg094ypZBSDHunmELIGOqhg5AxhbDX2nPPvfceCA1ZEQBEAQAAxiDGEGPIMSYlgxIxxyRkUiLn"
	"nJROSialpFZazKSEmEqLkXNOSiclk1JaC6llkkprJaYCAAACHAAAAiyEQkNWBABRAACIMUgppBRSSjGnmENKKceUY0gp5ZxyTjnH"
	"mHQQKucYdA5KpJRyjjmnnHMSMgeVcw5CJp0AAIAABwCAAAuh0JAVAUCcAACAkHOKMQgRYxBCCSmFUFKqnJPSQUmpg5JSSanFklKM"
	"lXNSOgkpdRJSKinFWFKKLaRUY2kt19JSjS3GnFuMvYaUYi2p1Vpaq7nFWHOLNffIOUqdlNY6Ka2l1mpNrdXaSWktpNZiaS3G1mLN"
	"KcacMymthZZiK6nF2GLLNbWYc2kt1xRjzynGnmusucecgzCt1ZxayznFmHvMseeYcw+Sc5Q6Ka11UlpLrdWaWqs1k9Jaaa3GkFqL"
	"LcacW4sxZ1JaLKnFWFqKMcWYc4st19BarinGnFOLOcdag5Kx9l5aqznFmHuKreeYczA2x547SrmW1nourfVecy5C1tyLaC3n1GoP"
	"Ksaec87B2NyDEK3lnGrsPcXYe+45GNtz8K3W4FvNRcicg9C5+KZ7MEbV2oPMtQiZcxA66CJ08Ml4lGoureVcWus91hp8zTkI0Vru"
	"KcbeU4u9156bsL0HIVrLPcXYg4ox+JpzMDrnYlStwcecg5C1FqF7L0rnIJSqtQeZa1Ay1yJ08MXooIsvAABgwAEAIMCEMlBoyIoA"
	"IE4AgEHIOaUYhEopCKGElEIoKVWMSciYg5IxJ6WUUloIJbWKMQiZY1Iyx6SEEloqJbQSSmmplNJaKKW1llqMKbUWQymphVJaK6W0"
	"llqqMbVWY8SYlMw5KZljUkoprZVSWqsck5IxKKmDkEopKcVSUouVc1Iy6Kh0EEoqqcRUUmmtpNJSKaXFklJsKcVUW4u1hlJaLKnE"
	"VlJqMbVUW4sx14gxKRlzUjLnpJRSUiultJY5J6WDjkrmoKSSUmulpBQz5qR0DkrKIKNSUootpRJTKKW1klJspaTWWoy1ptRaLSW1"
	"VlJqsZQSW4sx1xZLTZ2U1koqMYZSWmsx5ppaizGUElspKcaSSmytxZpbbDmGUlosqcRWSmqx1ZZja7Hm1FKNKbWaW2y5xpRTj7X2"
	"nFqrNbVUY2ux5lhbb7XWnDsprYVSWislxZhai7HFWHMoJbaSUmylpBhbbLm2FmMPobRYSmqxpBJjazHmGFuOqbVaW2y5ptRirbX2"
	"HFtuPaUWa4ux5tJSjTXX3mNNORUAADDgAAAQYEIZKDRkJQAQBQAAGMMYYxAapZxzTkqDlHPOScmcgxBCSplzEEJIKXNOQkotZc5B"
	"SKm1UEpKrcUWSkmptRYLAAAocAAACLBBU2JxgEJDVgIAUQAAiDFKMQahMUYp5yA0xijFGIRKKcack1ApxZhzUDLHnINQSuaccxBK"
	"CSGUUkpKIYRSSkmpAACAAgcAgAAbNCUWByg0ZEUAEAUAABhjnDPOIQqdpc5SJKmj1lFrKKUaS4ydxlZ767nTGnttuTeUSo2p1o5r"
	"y7nV3mlNPbccCwAAO3AAADuwEAoNWQkA5AEAEMYoxZhzzhmFGHPOOecMUow555xzijHnnIMQQsWYc85BCCFzzjkIoYSSOecchBBK"
	"6JyDUEoppXTOQQihlFI65yCEUkopnXMQSimllAIAgAocAAACbBTZnGAkqNCQlQBAHgAAYAxCzklprWHMOQgt1dgwxhyUlGKLnIOQ"
	"Uou5RsxBSCnGoDsoKbUYbPCdhJRaizkHk1KLNefeg0iptZqDzj3VVnPPvfecYqw1595zLwAAd8EBAOzARpHNCUaCCg1ZCQDkAQAQ"
	"CCnFmHPOGaUYc8w554xSjDHmnHOKMcacc85BxRhjzjkHIWPMOecghJAx5pxzEELonHMOQgghdM45ByGEEDrnoIMQQgidcxBCCCGE"
	"AgCAChwAAAJsFNmcYCSo0JCVAEA4AAAAIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQggh"
	"hBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEELonHPOOeec"
	"c84555xzzjnnnHPOOScAyLfCAcD/wcYZVpLOCkeDCw1ZCQCEAwAACkEopWIQSiklkk46KZ2TUEopkYNSSumklFJKCaWUUkoIpZRS"
	"SggdlFJCKaWUUkoppZRSSimllFI6KaWUUkoppZTKOSmlk1JKKaVEzkkpIZRSSimlhFJKKaWUUkoppZRSSimllFJKKaWEEEIIIYQQ"
	"QgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQCALgbHAAgEmycYSXprHA0uNCQlQBASAAAoBRzjkoIKZSQUqiYoo5CKSmkUkoK"
	"EWPOSeochVBSKKmDyjkIpaSUQiohdc5BByWFkFIJIZWOOugolFBSKiWU0jkopYQUSkoplZBCSKl0lFIoJZWUQiohlVJKSCWVEEoK"
	"naRUSgqppFRSCJ10kEInJaSSSgqpk5RSKiWllEpKJXRSQioppRBCSqmUEEpIKaVOUkmppBRCKCGFlFJKJaWSSkohlVRCCaWklFIo"
	"oaRUUkoppZJSKQAA4MABACDACDrJqLIIG0248AAUGrISACADAECUdNZpp0kiCDFFmScNKcYgtaQswxBTkonxFGOMOShGQw4x5JQY"
	"F0oIoYNiPCaVQ8pQUbm31DkFxRZjfO+xFwEAAAgCAASEBAAYICiYAQAGBwgjBwIdAQQObQCAgQiZCQwKocFBJgA8QERIBQCJCYrS"
	"hS4IIYJ0EWTxwIUTN5644YQObRAAAAAAABAA8AEAkFAAERHRzFVYXGBkaGxwdHh8gIQEAAAAAAAIAHwAACQiQERENHMVFhcYGRob"
	"HB0eHyAhAQAAAAAAAAAAQEBAAAAAAAAgAAAAQEBPZ2dTAATXGQAAAAAAAAAAAAACAAAAo+7EBxBXW3dnYGpqYmBoaWN7O1NRRE1h"
	"8DYDAJRrEnTbVKyrit+HVBPUwhhW0zpvMYy2/3vFEhzK7FmKJvptx7QP6axz0EqM1rqc6lLzWra7W1PnTik+HUM7jn3Irrzn9v0U"
	"K6wqKnXE0+YAZE8EsAB1AHh5JU54mrqVzs0xByNbfW+EBnSXBF6t0sHAz/+iNtZRPQ8nUTasORDXbsApfgNk6+nbfnHY8NblCnrt"
	"Vmk7+he25H2+KSGNpnfRW3irzxG752HqBjo6BQAAAPtVAIC2xURCkkeucm5OrOXd9VX6T7s+tn2kidsKE/HEx065yOWSmmMGqU09"
	"Ovz67DpXBWKeBihyFVKfwkqt9cLpU2564tw5vMks2p8Z8vfbhbpxKduBqlfr6pX7Eb3sV2TgyedNi53ivuQTnO1iqHAAfjoFAAAA"
	"u74LABRtxyQFzBa8Ijwuzkd+2ZSpBH3aoWkPni6tzlLdEQZxPKb8H0xYsXw9XCPRDRcWnNm8eNvNKu3/nOxO1v8nmz+jILtFVInR"
	"XHXHK0+Y3JWt0qwVnqg8XhzqObVaAp46BQAAADsJKEpO0vHiQdJZaHn3Kg+kVuLi/SO7QntU3poCLef3C+z40wuE5/Imi1bt52xF"
	"dybPKY8zjXs2BzrHSDJ4BVufA/fujEsbkWvzscgbfUezOeplukPp7cFCBT5KpQAAAHa2AKgYnJPTqL232leC+UjCTs6Sp12mRKe3"
	"o3qrlKh0H92MEye7zVJ7P7FerNcsnbKubdEh6534uFgigvGlXjnUnH+wsjyNILg5butOZGXWPW2To0RxMfuOktqHlhyjMHorcAr+"
	"GbUAAAD2ih0AKJ2cbcvndPYv6jombsdjTq1bnz3H5XyOy45QtCvog6kLpC/rlFGeXttzBH7P5ufMD+Gc4aWdSqXiFLE6UwcE9ydf"
	"L06Bx8VoSRsq3qSABXHsWl2J7Ai8KYqZoxRemNQCnjoFAAAA+wUAUHFikm6KqquOlzQYqRuLYhHthLU9LSAsBhSR/6KRChjlG++h"
	"p15sN3G5Q+2rWfV+b9omFFjgzivFqLpWC+Fx9mHHQHHr3Udjy7Fhrbs694f2mOQbza08GgC+KgUAAAA7Ayg6iUn90n1rYR0NnVU/"
	"0OUttZ/cHueFSmytu7I8z8/UnB2WuOdOC0lhj3bJjquNH4p+tnwW1J2a6Q1lWrh97pPerarSNCgoCiW3VjnpdJtti0fn9NQ7xQN+"
	"OgUAAACXB7ItZsslN2O3RkfT5lYfw0lhD2sRn3NIHRKpKq87rRaebupp6b6/mydrh0WUTRnDTSj0poG40zLadXeT9YRy0TlLJ99i"
	"4Qb8LaMcIK9LgAeX0l+QrNL0Mi5MpcZ5c0/jAb4p9QAAAPabCQAoMjHm9OiZhSfTmmzpLNkqoZoPHScRwg2FoDi2WKvgYjpS18u9"
	"iFo+CPvS7hXJ3GMtuDd40yrlnBjXxdkuZ2A5ZzNZpWBep3kvCuwmlQV4i1XUrrGnnPdS6UE76P0dDZ46BQAAANcAirLlpLfn754t"
	"oxIemUq7ZEkN41dAzAvMi3QpHCHRQasTCJXLWBAlhK37vM8d3rWSTqxUfhRGjy4sJeJTb9k/xcV87h1QGF7bSqey+Htc1foJLYQ1"
	"6ff0TILTD3ZKZQAAAC6AttWmbUtf2IbunmAsRmWc9LExLNPbEu993Rze5UGYdkSyi+Po7RYTtfZqb1ZMmwl9IFx+zNpG9aG8dFI1"
	"ia4c9cPW6zlNYk5sh1GjLxJ6JKv3bhIGhfifUdiFQ4iX7Q+1WuUDuW7IkgNOI+4Xb71D/3MmA2RXPcQNQIh4ctHqjtFosDxIbg1N"
	"bsajh24l0IwQm/BCeQ6WmpaZ0bNiTfgfV9t9aQrWE+scJ0F3abAARE8AuIgHAC5xvXf2dp+13ZyYT6iGXmzmt6HMJM+BS2O43Jpp"
	"k/rHaTNn6mel7D7iwXFdObPu3JGQEd0ywEC47s7GCVLpJ8XJz0BfN6WNahKIzB1ES2iwBXBO/2v12/YbD8fRZqlPnAbmvyMexemX"
	"8Ul5P0XkqHnxp/n5P0VQZzAQHFSnE5x1NmHblWOA5APzAMWpZ6kve4qdzP8xAp0XAMr+8kI=";
static const uint32 kVorbis_A3_Size = 5003;

static const char *const kVorbis_B =
	"T2dnUwACAAAAAAAAAAAAAAAAAAAAAGKfnjEBHgF2b3JiaXMAAAAAAkSsAAAAAAAAAHcBAAAAAAC4AU9nZ1MAAAAAAAAAAAAAAAAA"
	"AAEAAACyAUinEDD//////////////////+IDdm9yYmlzBgAAAGZmbXBlZwEAAAAWAAAAZW5jb2Rlcj1MYXZjIGxpYnZvcmJpcwEF"
	"dm9yYmlzJUJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSgQohbKIHQkFUAAEAAAIdBeBSEikEIIYQl"
	"PViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRFOWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMG"
	"OegchMIsKIqCxDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgUhMtBqBqEKjkIH4Qg"
	"NGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAAAQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7Is"
	"yzIQGrIKAEgAAFBRDEVxFAcIDVkFAGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
	"bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa0535zjoFkOmkqxOR2cSLV5kpuKuTnn"
	"nHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCexedCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlS"
	"m0u1Oeecc84555xzzjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQho1h3CkI0udo"
	"IEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJIIYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPM"
	"Mssss8w67KyzDjsMMcQQQyutxFJTbTXWWGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQ"
	"VQAAIACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33fd33fd34dWFYlmVZlmVZlmVZ"
	"lmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQCA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXT"
	"NFXRFV1RN21RNmXTNV1TNl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBoyCoAQAYA"
	"QAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6"
	"ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguEhqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3R"
	"Ez3TU0VXdIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
	"VU3TNE0TCA1ZCQCQAQCgEFtLrcXcCWocYtJyzCR0TmIQqrEIIke1t8oxpRzFnhqIlFESe6ooY4pJzDG00CknrdZSOoUUpJhTChVS"
	"DlogNGSFABCaAeBwHECyLECyNAAAAAAAAACQNA3QPA+wPA8AAAAAAAAAJE0DLE8DNM8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEDSNEDzPEDzPAAAAAAAAADQPA/wRBHwRBEAAAAAAAAA"
	"LM8DPNEDPFEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AMDRNEDzPEDzPAAAAAAAAACwPA/wRBHwPBEAAAAAAAAANM8DPFEEPFEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQ4AAAEGAhFBqyIgCIEwAw"
	"OA40DZoGzwM4lgXPg+dBFAGOZcHz4HkQRQAAAAAAAAAAAAA0z4OqQlXhqgDN82CqUFWoLgAAAAAAAAAAAACW50FVoapwXYDleTBV"
	"mCpUFQAAAAAAAAAAAABPFKG6UF24KsAzRbgqXBWqCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAYcAAACDChDBQasiIAiBMAcDiK"
	"ZQEAgOM4lgUAAI7jWBYAAFiWJYoAAGBZmigCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"AAAAAAAAAAAAAAAAAAAAAAgAABhwAAAIMKEMFBqyEgCIAgAwKIplAcuyLGBZlgU0zbIAlgbQPIDnAUQRAAgAAChwAAAIsEFTYnGA"
	"QkNWAgBRAAAGRbEsTRNFmqZpmiaKNE3TNE0UeZ6meZ5pQtM8zzQhip5nmhBFzzNNmKYoqioQRVUVAABQ4AAAEGCDpsTiAIWGrAQA"
	"QgIADI5iWZ4niqIoiqapqjRN0zxPFEXRNFXVVWmapnmeKIqiaaqq6vI8TRNF0xRF01RV14WmiaJpmqJpqqrrwvNE0TRNU1VV1XXh"
	"eaJomqapqq7ruhBFUTRN01RV13VdIIqmaZqq6rqyDETRNFVVVV1XloEomqaqqqrryjIwTdNUVdeVXVkGmKaquq4syzJAVV3XdWVZ"
	"tgGq6rquK8uyDXBd15VlWbZtAK4ry7Js2wIAAA4cAAACjKCTjCqLsNGECw9AoSErAoAoAADAGKYUU8owJiGkEBrGJIQSQiYllZRK"
	"qiCkUlIpFYRUUiolo5JSailVEFIpKZUKQiqllVQAANiBAwDYgYVQaMhKACAPAIAgRinGGGMMMqYUY845B5VSijHnnJOMMcaYc85J"
	"KRljzDnnpJSMOeecc1JK5pxzzjkppXPOOeeclFJK55xzTkopJYTOOSellNI555wTAABU4AAAEGCjyOYEI0GFhqwEAFIBAAyOY1ma"
	"pmmeJ4qWJGma53meKJqmZkma5nmeJ4qmyfM8TxRF0TRVled5niiKommqKtcVRdM0TVVVVbIsiqZpmqrqujBN01RV13VlmKZpqqrr"
	"ui5s21RV1XVlGbatmqoqu7IMXFd1Zde2geu6ruzatgAA8AQHAKACG1ZHOCkaCyw0ZCUAkAEAQBiDjEIIIYUQQgohhJRSCAkAABhw"
	"AAAIMKEMFBqyEgBIBQAAkLHWWmuttdZARymllFJKqXCMUkoppZRSSimllFJKKaWUSkoppZRSSimllFJKKaWUUkoppZRSSimllFJK"
	"KaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKBQAuVTgA6D7YsDrCSdFYYKEhKwGAVAAAwBilmHJO"
	"QikVQow5JiGlFiuEGHNOSkoxFs85B6GU1losnnMOQimtxVhU6pyUlFqKragUMikppdZiEMKUlFprpbUghCqpxJZaa0EIXVNqKZbY"
	"ghC2tpJSjDEG4YOPsZVYagw++CBbKzHVWgAAZoMDAESCDasjnBSNBRYashIACAkAIIxRijHGGHPOOeckY4wx5pxzEEIIoWSMMeec"
	"cw5CCCGUzjnnnHMQQgghhFJKx5xzDkIIIYRQUuqccxBCCKGEEEoqnXMOQgghhFJKSaVzEEIIoYRQQkklpdQ5CCGEEEIpKaWUQggh"
	"hBJCKCWllFIIIYQQQiihpJRSCiGEUkIIpZSUUkophRBKCKWUklJJKaUSSgkhhFJSSSmlFEIIJZRSSioppZRKCaGEUkoppaSUUkoh"
	"lFBCKQUAABw4AAAEGEEnGVUWYaMJFx6AQkNWAgBkAACUslJKKK1VQCKlGKTaQkeZgxRziSxzDFrNpWIOKQathsoxpRi0FjIImVJM"
	"SgkldUwpJy3FmErnnKSYc42lcxAAAABBAICAkAAAAwQFMwDA4ADhcxB0AgRHGwCAIERmiETDQnB4UAkQEVMBQGKCQi4AVFhcpF1c"
	"QJcBLujirgMhBCEIQSwOoIAEHJxwwxNveMINTtApKnUgAAAAAAAMAPAAAJBcABER0cxhZGhscHR4fICEiIyQCAAAAAAAGAB8AAAk"
	"JUBERDRzGBkaGxwdHh8gISIjJAEAgAACAAAAACCAAAQEBAAAAAAAAgAAAAQET2dnUwAErjMAAAAAAAAAAAAAAgAAALs65FYQMyZt"
	"TElIS0hKS0tKSkvC5YzpqyD126V/MJXasX44/31aIqlA15ji7OqGbexwjOdwrE366tWrV68iJaqiKqpEIpFIBJTrq0sd7rb+EdGT"
	"fQABAAAAAMB+aSH0evrbFZNSv3tcd91GJBJReop+okNrkngluCMBPtH7sJv02wX4HiHgGwAAAIADAAAAAAAAAAAAAAAAAAAAABCj"
	"j56Rsfr5gwWM6w6QhmO5djQMbviZH+6YN/8zJtp9j093n5k8Y/Pr52bqWTPap//9/v3+/f79ft59a5p5Bf6ZvpKnQGwoEcFJB0bR"
	"R+YudTpHh++pAN8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOcP7wPcvPkGAAAU0MRN31vnZwL4Z9UM39xWCACemn7CU/+GEgZOqGAU"
	"fWTuUqdzTPieCvANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDufgT038cAAABQDsaLFvuGAXi84nHRfwoAHpq+Eaf+DSUGcIBR9BHe"
	"pU7nKPieauAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOC8uwHX128CAABARha/Ba8D+ArPvXW+sAgA/pm+kqdAbCgRwUkHRtFHcJfa"
	"naPge6oC3wAAACIBAAAAAAAAAAAAAAAAAAAAAAAAAOc/d0D3n+sAACigenPrN//NBOCtbd88OgQAnpp+wlP/hhIBnFDBKHobXKWi"
	"HAXfUwa+AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe9iPgTW8AAACAxTX//bd1GKCI1zu/oRAAHpq+Eaf+DSUGcIBR9BHepU7nKPie"
	"qsA3AACAKAAAAAAAAAAAAAAAAAAAAAAAAADg8d0NDP9ZHwAAAMjI8Dezal4H4L/z//1/AwD+mb6Sp0BqKNHASQNG0UfmLnU6R4fv"
	"qQa+AQAAAAAAAAAAAAAAAAAAAAAAAAAAAADOf+4A1zdvAgBAAdWb35y7MRPAV+S7Ee8qAgCemn7CUyA2lIjgRO+AUfSRuUudztHh"
	"e2qBbwAAAAAAAAAAAAAAAAAAAAAAAAAAAACAh4dHQP+lowMAAMBwzetd5xYD8Kh+btb/CgAemr4Rp/4NJQZwgFH0kblLnc7R4Xuq"
	"gW8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMd3N+DmjTcAAAAgI8Pnvh2+AeCfOex7a2shAP6ZvnKnQJkoMYCTBoyij8xd6nKODt9T"
	"Br4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPznDjB+vwYAgCIobx3aOjwTQM+fH0586wMAnpp+wlMgNZSI4ET3gFH0kblLXc7R4Xsq"
	"wDcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMPDI6D/fgMAAACGa24MPzoIIOe/+a/osR8APnp+KNvZfsRHg51Hg07zPvwu/XEm43uE"
	"BR+sXA+9M7744aHvbYx18pt/kgRVEBEJNqFhGIZhGAAAAAAAoNIGky/FHo2+0b57Cf5MXv1+WbpxeK39sNyN4+KxTz5nt+PIftZ7"
	"xKe2N/ZPbWGv7Y19Zwt7PV7mdspP6Ss/PrfzMqWv/JS+8uNlbmffbRv7zrbx2W0v+8672T9sL5+dd7Pv3M7LlLb8lL58YlZ/opVo"
	"xfJZ9WV9Ocgh4wyokAEFcHCAAwC+Jz0yz9nbxK8bJpAnPTfuIUK4C2CGBS7ge22u0zdMQQS54P7hMAwDAADkE8UbfaQNdKbrk6eX"
	"J4/l/VEzbSDp3ejuDQeulw+dNbp/xsr20Oo9tysZu9P05s3LZnlxGG7PYZXHuHQO836sec84j7lHs53RVDqlMZpT1bBTn28MeRi/"
	"uze7hylGc6oaNJU1uszNKuuiS5t1yrjoUlmndNFUOv42+1bElb3N7s3x/fFn9q2IK8dtdm/W9sf3p7fZpIizvc3uVW1/eoqkSGzP"
	"7l7VVtOTQ5EYZ4vWVu1yyKjQgBxAAXAA";
static const uint32 kVorbis_B_Size = 5424;

static const char *const kVorbis_C =
	"T2dnUwACAAAAAAAAAAAAAAAAAAAAANabov8BHgF2b3JiaXMAAAAAASJWAAAAAAAA0AEBAAAAAACpAU9nZ1MAAAAAAAAAAAAAAAAA"
	"AAEAAADQiUDRDzD/////////////////4AN2b3JiaXMGAAAAZmZtcGVnAQAAABYAAABlbmNvZGVyPUxhdmMgbGlidm9yYmlzAQV2"
	"b3JiaXMkQkNWAQBAAAAYQhAqBa1jjjrIFSGMGaKgQsopxx1C0CGjJEOIOsY1xxhjR7lkikLJgdCQVQAAQAAApBxXUHJJLeecc6MY"
	"V8xx6CDnnHPlIGfMcQkl55xzjjnnknKOMeecc6MYVw5yKS3nnHOBFEeKcacY55xzpBxHinGoGOecc20xt5JyzjnnnHPmIIdScq41"
	"55xzpBhnDnILJeecc8YgZ8xx6yDnnHOMNbfUcs4555xzzjnnnHPOOeecc4wx55xzzjnnnHNuMecWc64555xzzjnnHHPOOeeccyA0"
	"ZBUAkAAAoKEoiuIoDhAasgoAyAAAEEBxFEeRFEuxHMvRJA0IDVkFAAABAAgAAKBIhqRIiqVYjmZpniZ6oiiaoiqrsmnKsizLsuu6"
	"LhAasgoASAAAUFEUxXAUBwgNWQUAZAAACGAoiqM4juRYkqVZngeEhqwCAIAAAAQAAFAMR7EUTfEkz/I8z/M8z/M8z/M8z/M8z/M8"
	"z/M8DQgNWQUAIAAAAIIoZBgDQkNWAQBAAAAIIRoZQ51SElwKFkIcEUMdQs5DqaWD4CmFJWPSU6xBCCF87z333nvvgdCQVQAAEAAA"
	"YRQ4iIHHJAghhGIUJ0RxpiAIIYTlJFjKeegkCN2DEEK4nHvLuffeeyA0ZBUAAAgAwCCEEEIIIYQQQggppJRSSCmmmGKKKcccc8wx"
	"xyCDDDLooJNOOsmkkk46yiSjjlJrKbUUU0yx5RZjrbXWnHOvQSljjDHGGGOMMcYYY4wxxhgjCA1ZBQCAAAAQBhlkkEEIIYQUUkgp"
	"pphyzDHHHANCQ1YBAIAAAAIAAAAcRVIkR3IkR5IkyZIsSZM8y7M8y7M8TdRETRVV1VVt1/ZtX/Zt39Vl3/Zl29VlXZZl3bVtXdZd"
	"Xdd1Xdd1Xdd1Xdd1Xdd1XdeB0JBVAIAEAICO5DiO5DiO5EiOpEgKEBqyCgCQAQAQAICjOIrjSI7kWI4lWZImaZZneZaneZqoiR4Q"
	"GrIKAAAEABAAAAAAAICiKIqjOI4kWZamaZ6neqIomqqqiqapqqpqmqZpmqZpmqZpmqZpmqZpmqZpmqZpmqZpmqZpmqZpmqZpAqEh"
	"qwAACQAAHcdxHEdxHMdxJEeSJCA0ZBUAIAMAIAAAQ1EcRXIsx5I0S7M8y9NEz/RcUTZ1U1dtIDRkFQAACAAgAAAAAAAAx3M8x3M8"
	"yZM8y3M8x5M8SdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TdM0TQNCQ1YCAGQAABzFmHtSSqnOQUgxJ2c7"
	"xhy0mJsOFUJMWi02ZIgYJq3H0ilCkKOaSsiQMYpqKaVTCCmppZTQMcakptZaKqW0HggNWREARAEAAAghxhBjiDEGIYMQMcYgdBAi"
	"xhyEDEIGIZQUSskghBJCSZFjDEIHIYMQUgmhZBBCKSGVAgAAAhwAAAIshEJDVgQAcQIACELOIcYgRIxBCCWkFEJIKWIMQuaclMw5"
	"KaWU1kIpqUWMQcick5I5JyWU0lIppbVQSmullNZCKa211mpNrcUaSmktlNJaKaW11FqNrbUaI8YgZM5JyZyTUkpprZTSWuYclQ5C"
	"Sh2ElEpKLZaUWsyck9JBR6WDkFJJJbaSUowlldhKSjGWlGJsLcbaYqw1lNJaSSW2klKMLbYaW4w1R4xByZyTkjknpZTSWimptcw5"
	"KR2ElDoHJZWUYiwltZg5J6WDkFIHIaWSUmwlpdhCKa2VlGIsJbXYYsy1tdhqKKnFklKMJaUYW4y1tthq7KS0FlKJLZTSYoux1tZa"
	"raGUGEtKMZaUYowx1txirDmU0mJJJcaSUosttlxbjDWn1nJtLdbcYsw1xlx7rbXn1FqtqbVaW4w1xxpzrLXm3kFpLZQSWyipxdZa"
	"rS3GWkMpsZWUYiwlxdhizLW1WHMoJcaSUowlpRhbjLXGGHNOrdXYYsw1tVZrrbXnGGvsqbVaW4w1t9hqrbX2XnPstQAAgAEHAIAA"
	"E8pAoSErAYAoAADCGKUYg9AgpJRjEBqElGIOQqUUY85JqZRizDkpmWPOQUglY845CCWFEEpJJaUQQiklpVQAAECBAwBAgA2aEosD"
	"FBqyEgAICQAgEFKKMecglJJSShFCTDkGIYRSUmotQkgp5hyEUEpKrVVMMeYchBBKSam1SjHGnIMQQikptZY55xyEEEpJKaXWMuac"
	"gxBCKSml1FoHIYQQSiklpdZa6yCEEEIppaTUWmshhBBKKaWklFqLMYQQQimlpJJSazGWUkpJKaWUUmstxlJKKSmllFJLrcWYUkop"
	"pdZaay3GGFNKKaXUWmuxxRhjaq211lqLMcYYa02ttdZaizHGGGOtBQAAHDgAAAQYQScZVRZhowkXHoBCQ1YEAFEAAIAxiDHEGHKO"
	"QcigRM4xCZmEyDlHpZOSSQmhldYyKaGVklrknJPSUcqolJZCaZmk0lpooQAAsAMHALADC6HQkJUAQB4AAIGQUow55xxSijHGnHMO"
	"KaUYY845pxhjzDnnnFOMMeacc84xxpxzzjnnGGPOOeecc84555xzDkLnnHPOOQehc8455yCE0DnnnHMQQigAAKjAAQAgwEaRzQlG"
	"ggoNWQkApAIAAMgw5pxzUlJqlGIMQgilpNQoxRiEEEpJKXMOQgilpNRaxhh0EkpJqbUOQiilpNRajB2EEkpJqbUYOwilpJRSazF2"
	"EEpJqaXWYiylpNRaazHWWkpJqbXWYqw1pdRajDHWWmtKqbUYY6y11gIAwBMcAIAKbFgd4aRoLLDQkJUAQAYAwBAAwAEAAAMOAAAB"
	"JpSBQkNWAgCpAACAMYw55xyEUhqlnIMQQimpNEo5ByGEUlLKnJNQSikptZY5J6WUUlJqrYNQSkoptRZjB6GUlFJqLcYOQioptRZj"
	"jR2EUlJqLcYYQykptRZjjLWGUlJqLcYYay0ptRZjjbXmWlJqLcYaa821AACEBgcAsAMbVkc4KRoLLDRkJQCQBwBAIMQYY4w5h5Ri"
	"jDHnnENKMcaYc84xxhhzzjnnGGOMOeecc4wx55xzzjnGmHPOOeccc84555xzjjnnnHPOOeecc84555xzzjnnnHPOCQAAKnAAAAiw"
	"UWRzgpGgQkNWAgDhAACAMYw5xxh0ElJqmIIOQgglpNBCo5hzEEIopaTUMuikpFRKSq3FljknpaRSUkqtxQ5CSiml1FqMMXYQUkop"
	"pdZijLWDUEpKLcVYY60dhFJSaq21GGsNpaTUWmwx1ppzKCWl1lqMsdaaS0qtxVhjrbnmXFJqLbZYa60159RajDHWmmvOvafWYoyx"
	"1ppz7r0AAJMHBwCoBBtnWEk6KxwNLjRkJQCQGwCAIMSYc85BCCGEEEIIIVKKMecghBBCCCGUUkqkFGPOQQghhBBCCCGEjDHnoIMQ"
	"QgillFJKKRljzkEIIYQQSiilhBI656CDEEIJpZRSSimldM45CCGEEEoppZRSSukghBBCCKWUUkoppZTSQQghhFBKKaWUUkopJYQQ"
	"QgillFJKKaWUUkoIIYQQSimllFJKKaWUEEIIpZRSSimllFJKKSGEEEoppZRSSimllFJCCKWUUkoppZRSSimlhBBKKaWUUkoppZRS"
	"SgmhlFJKKaWUUkoppZQSSimllFJKKaWUUkopJZRSSimllFJKKaWUUkoopZRSSimllFJKKaWUUEoppZRSSimllFJKKaGUUkoppZRS"
	"SimllFIKAAA6cAAACDCi0kLsNOPKI3BEIcMEVGjISgAgHAAAQAQ6CCGEEEIIEXMQQgghhBBCiJiDEEIIIYQQQgghhBBCCKWUUkop"
	"pZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkop"
	"pZRSSimllFJKKaWUUkoppZRSSimllFJKKaUUAHWZ4QAYPWHjDCtJZ4WjwYWGrAQA0gIAAGMYY4wpyKSzFmOtDWMQQgedhBRqqCWm"
	"hjEIIXRQSkottlhzBqGkUkpJLcZYg809g1BKKaWkFmOtORfjQUglpdRiq7XnHIzuIJSSUkox1ppz7r1o0ElJqbVac+49B188CKWk"
	"1lqMPQcfjDCilJZirLHWHHwRRhhRSkstxpp7zb0YY4RKKcZae86551yMET6lFmOuufcefC7C+OJizDn34oMPPghhjJAx5thz8L0X"
	"Y4wPwshccy7CGOOLMML4IGytuQdfjBFGGGN87zX4oHsxwggjjDHCCN1z0UX4YowxRhhfhAEAuREOAIgLRhJSZxlWGnHjCRgikEJD"
	"VgEAMQAABDHGIKSQUkopxRhjjDHGGGOMMcYYY4wxxpxjzjnnnAAAwAQHAIAAK9iVWVq1UdzUSV70QeATOmIzMuRSKmZyIuiRGmqx"
	"EuzQCm7wArDQkJUAABkAAOSklJRaLRpCykFpNYjIIOUkxSQiY5CC0oKnkDGIScodYwohBal20DGFFKMaUgqZUgpqqjmGjjGoMSfh"
	"UgmlBgAAQBAAICAkAMAAQcEMADA4QBg5EOgIIHBoAwAMRMhMYFAIDQ4yAeABIkIqAEhMUJQudEEIEaSLIIsHLpy48cQNJ3RogwAA"
	"AAAAgACADwCAhAKIiGZmrsLiAiNDY4Ojw+MDJERkJAAAAAAAQADgAwAgIQEiopmZq7C4wMjQ2ODo8PgACREZCQAAAAAAAAAAAAIC"
	"AgAAAAAAAQAAAAICT2dnUwAE1xkAAAAAAAAAAAAAAgAAAFhmP1MPbSEeIB0dIB4fHR8dIT5q3I7tABljuP2zSgGAwUC2IlappPwN"
	"1TPl9nj1aP3j4ePhY3VanVZ7mqd52s7aWTtrZ+2snbWzdhaqrdXO2lkwBmMwBmMwBmMwBmMwBmMwBmMwOoINRofDsf3tt99+++23"
	"33777bfffvvtt99+C/oJ2u1EAaA/rE4AAAAAAAAAuB4FAAAAGDBsX2n+HMwBAJ5q2uylBmBAd1gtgP++AQAAAAAAAIDQU9rpVaIA"
	"AJ6KWu8EAOgXVicAAAAAAAAA6FIAAAAAgLi8fY+/HQAAPpva7wEAA2DDagF8/d4DAAAAAAAAAFBRx0bJAAD+itrtCQAMOB1WC+DB"
	"mAMAAAAAAAAAdPjgd94AAB5aWo6qAdADqxMAAAAAAAAA9iIAAAAAYHSL7fRZCgAA/tk53VEGoLwEqwXwlyoAAAAAAAAAUOn08Pv9"
	"lSgB3vnZ3KsOoLwKqwXw6QVLAAAAAAAAAEZsCqnuC2QDAF5aWu+gARgAhNUC+O/vAAAAAAAAAADtP9xE2VEAXoqa9yoA9MDqBAAA"
	"AAAAAABdBAAAAABIhxi//TsAAD6b2u8BAAPghNUC+O1XAAAAAAAAAAAqfqslaQAAHova7wEAA2BgdQIAAAAAAADA+UQAAAAAQHF+"
	"WxTfAAAA3kka9/QEoNkd4B6Ant4+gCEEAACA0G0pI/HmffIxv1iZWHX7vbX5rJYAgHJWy1ktZ7Wc7Z08V8tZLWe1nAFeF5nPat8A"
	"zwBwL4Dh+tw5oJgiAAAAOZJWzMXECX5fdbXGfKZk0p25HKYM/zJMt9dfhinDZXfmx/6mj/1NH/ubPvY3fexv+ujOXHZnfhEyjy9C"
	"Zi67M5fdmz72N33sl8coj1EeozxGeQwA";
static const uint32 kVorbis_C_Size = 4374;


namespace {

struct Clip {
	const char *b64;
	uint32 size;
};

const Clip kA1 = { kVorbis_A1, kVorbis_A1_Size };
const Clip kA2 = { kVorbis_A2, kVorbis_A2_Size };
const Clip kA3 = { kVorbis_A3, kVorbis_A3_Size };
const Clip kB = { kVorbis_B, kVorbis_B_Size };
const Clip kC = { kVorbis_C, kVorbis_C_Size };

Audio::SeekableAudioStream *openClip(const Clip &c) {
	Common::String s(c.b64);
	Common::SeekableReadStream *in = Common::b64DecodeStream(s, c.size);
	if (!in)
		return nullptr;
	return Audio::makeVorbisStream(in, DisposeAfterUse::YES);
}

// Reads what is left of the stream in chunks of n samples.
Common::Array<int16> readAll(Audio::AudioStream *s, int n = 1000) {
	Common::Array<int16> out;
	int16 buf[4096];
	assert(n <= 4096);
	for (;;) {
		const int got = s->readBuffer(buf, n);
		for (int i = 0; i < got; ++i)
			out.push_back(buf[i]);
		if (got < n || s->endOfData())
			break;
	}
	return out;
}

Common::Array<int16> decodeClip(const Clip &c) {
	Audio::SeekableAudioStream *s = openClip(c);
	Common::Array<int16> out;
	if (s)
		out = readAll(s);
	delete s;
	return out;
}

// Seeks to a few places (and back to the start) and reads some samples after
// each, the way a looping or resumed speech line would.
Common::Array<int16> seekTrace(const Clip &c) {
	static const int kFrames[] = { 0, 2756, 5512, 811, 0, 8000, 4410, 0 };
	Audio::SeekableAudioStream *s = openClip(c);
	Common::Array<int16> out;
	if (!s)
		return out;
	const int ch = s->isStereo() ? 2 : 1;
	int16 buf[700 * 2];
	for (uint i = 0; i < ARRAYSIZE(kFrames); ++i) {
		out.push_back(s->seek(Audio::Timestamp(0, kFrames[i], s->getRate())) ? 1 : 0);
		const int got = s->readBuffer(buf, 700 * ch);
		out.push_back(got);
		for (int j = 0; j < got; ++j)
			out.push_back(buf[j]);
	}
	s->rewind();
	Common::Array<int16> rest = readAll(s, 333);
	out.push_back(rest.size());
	for (uint j = 0; j < rest.size(); ++j)
		out.push_back(rest[j]);
	out.push_back(s->getLength().totalNumberOfFrames());
	delete s;
	return out;
}

const Clip *const kClips[] = { &kA1, &kA2, &kA3, &kB, &kC };

} // End of anonymous namespace

#endif

// cxxtestgen still discovers the class in a conditional block; module.mk
// excludes this file entirely unless the cache is built.
class VorbisSetupCacheTestSuite : public CxxTest::TestSuite {
public:
	void setUp() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::VorbisSetupCache::setEnabled(true);
		Audio::VorbisSetupCache::setCapacity(Audio::VorbisSetupCache::kDefaultCapacity);
		Audio::VorbisSetupCache::clear();
#endif
	}

	void tearDown() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		setUp();
#endif
	}

	void test_clips_decode() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		for (uint i = 0; i < ARRAYSIZE(kClips); ++i)
			TS_ASSERT_LESS_THAN(5000u, decodeClip(*kClips[i]).size());
#endif
	}

	void test_pcm_identical_with_and_without_cache() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Common::Array<int16> plain[ARRAYSIZE(kClips)];
		Audio::VorbisSetupCache::setEnabled(false);
		for (uint i = 0; i < ARRAYSIZE(kClips); ++i)
			plain[i] = decodeClip(*kClips[i]);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 0u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 0u);

		Audio::VorbisSetupCache::setEnabled(true);
		// Twice: the first pass fills the cache, the second hits every clip.
		for (int pass = 0; pass < 2; ++pass)
			for (uint i = 0; i < ARRAYSIZE(kClips); ++i)
				TS_ASSERT(decodeClip(*kClips[i]) == plain[i]);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 3u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 7u);
#endif
	}

	void test_nonseekable_stream_is_uncached() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::VorbisSetupCache::setEnabled(false);
		const Common::Array<int16> expected = decodeClip(kA1);
		Audio::VorbisSetupCache::setEnabled(true);
		Common::String data(kA1.b64);
		Common::SeekableReadStream *raw = Common::b64DecodeStream(data, kA1.size);
		TS_ASSERT(raw);
		if (!raw)
			return;
		class NonSeekable : public Common::SeekableReadStream {
		public:
			explicit NonSeekable(Common::SeekableReadStream *s) : _s(s) {}
			~NonSeekable() { delete _s; }
			uint32 read(void *dst, uint32 n) override { return _s->read(dst, n); }
			bool eos() const override { return _s->eos(); }
			bool err() const override { return _s->err(); }
			void clearErr() override { _s->clearErr(); }
			int64 pos() const override { return _s->pos(); }
			int64 size() const override { return _s->size(); }
			bool seek(int64, int = SEEK_SET) override { return false; }
		private:
			Common::SeekableReadStream *_s;
		};
		Audio::SeekableAudioStream *s = Audio::makeVorbisStream(new NonSeekable(raw), DisposeAfterUse::YES);
		TS_ASSERT(s);
		if (s)
			TS_ASSERT(readAll(s) == expected);
		delete s;
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 0u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 0u);
#endif
	}

	void test_rewind_failure_replays_headers_without_sharing() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::VorbisSetupCache::setEnabled(false);
		const Common::Array<int16> expected = decodeClip(kA1);
		Audio::VorbisSetupCache::setEnabled(true);
		Common::String data(kA1.b64);
		Common::SeekableReadStream *raw = Common::b64DecodeStream(data, kA1.size);
		TS_ASSERT(raw);
		if (!raw)
			return;
		class FailingRewind : public Common::SeekableReadStream {
		public:
			explicit FailingRewind(Common::SeekableReadStream *s) : _s(s) {}
			~FailingRewind() { delete _s; }
			uint32 read(void *dst, uint32 n) override { return _s->read(dst, n); }
			bool eos() const override { return _s->eos(); }
			bool err() const override { return _s->err(); }
			void clearErr() override { _s->clearErr(); }
			int64 pos() const override { return _s->pos(); }
			int64 size() const override { return _s->size(); }
			bool seek(int64 offs, int whence = SEEK_SET) override {
				if (whence == SEEK_SET && offs == 0 && _s->pos() > 0)
					return false;
				return _s->seek(offs, whence);
			}
		private:
			Common::SeekableReadStream *_s;
		};
		Audio::SeekableAudioStream *s = Audio::makeVorbisStream(new FailingRewind(raw), DisposeAfterUse::YES);
		TS_ASSERT(s);
		if (s)
			TS_ASSERT(readAll(s) == expected);
		delete s;
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 0u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 0u);
#endif
	}

	void test_decode_error_does_not_invalidate_shared_setup() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::SeekableAudioStream *valid = openClip(kA1);
		TS_ASSERT(valid);
		if (!valid)
			return;
		Common::String data(kA2.b64);
		Common::SeekableReadStream *raw = Common::b64DecodeStream(data, kA2.size);
		TS_ASSERT(raw);
		if (!raw) {
			delete valid;
			return;
		}
		class Truncated : public Common::SeekableReadStream {
		public:
			explicit Truncated(Common::SeekableReadStream *s) : _s(s), _reads(0), _failed(false) {}
			bool failed() const { return _failed; }
			~Truncated() { delete _s; }
			uint32 read(void *dst, uint32 n) override {
				if (++_reads > 1) {
					_failed = true;
					return 0;
				}
				return _s->read(dst, n);
			}
			bool eos() const override { return _s->eos(); }
			bool err() const override { return _s->err() || _failed; }
			void clearErr() override { _failed = false; _s->clearErr(); }
			int64 pos() const override { return _s->pos(); }
			int64 size() const override { return _s->size(); }
			bool seek(int64 offs, int whence = SEEK_SET) override { return _s->seek(offs, whence); }
		private:
			Common::SeekableReadStream *_s;
			uint _reads;
			bool _failed;
		};
		Truncated *input = new Truncated(raw);
		Audio::SeekableAudioStream *broken = Audio::makeVorbisStream(input, DisposeAfterUse::NO);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 1u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().entries, 1u);
		if (broken) {
			int16 samples[200];
			for (int i = 0; i < 20; ++i)
				broken->readBuffer(samples, 200);
		}
		delete broken;
		TS_ASSERT(input->failed());
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().entries, 1u);
		delete input;
		TS_ASSERT_LESS_THAN(5000u, readAll(valid).size());
		delete valid;
#endif
	}

	void test_second_open_with_same_setup_hits() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		delete openClip(kA1);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 1u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 0u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().entries, 1u);
		delete openClip(kA2);	// another clip, same setup header
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 1u);
		delete openClip(kB);	// another setup header
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 2u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().entries, 2u);
		delete openClip(kA3);
		delete openClip(kA1);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 3u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 2u);
#endif
	}

	void test_seek_and_rewind_identical() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::VorbisSetupCache::setEnabled(false);
		const Common::Array<int16> plainA2 = seekTrace(kA2), plainB = seekTrace(kB);
		Audio::VorbisSetupCache::setEnabled(true);
		delete openClip(kA1);	// so A2 opens on a cached setup
		delete openClip(kB);
		TS_ASSERT(seekTrace(kA2) == plainA2);
		TS_ASSERT(seekTrace(kB) == plainB);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 2u);
#endif
	}

	void test_streams_sharing_a_setup_decode_interleaved() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::VorbisSetupCache::setEnabled(false);
		const Common::Array<int16> plain1 = decodeClip(kA1), plain2 = decodeClip(kA2);
		Audio::VorbisSetupCache::setEnabled(true);
		Audio::SeekableAudioStream *s1 = openClip(kA1);
		Audio::SeekableAudioStream *s2 = openClip(kA2);
		TS_ASSERT(s1 && s2);
		if (!s1 || !s2)
			return;
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 1u);
		Common::Array<int16> got1, got2;
		int16 buf[500];
		for (int i = 0; i < 6; ++i) {
			int n = s1->readBuffer(buf, 500);
			for (int j = 0; j < n; ++j)
				got1.push_back(buf[j]);
			n = s2->readBuffer(buf, 500);
			for (int j = 0; j < n; ++j)
				got2.push_back(buf[j]);
		}
		// The cache lets go of the setup and the first stream ends: the
		// second one still has it.
		Audio::VorbisSetupCache::clear();
		Common::Array<int16> rest1 = readAll(s1);
		delete s1;
		Common::Array<int16> rest2 = readAll(s2);
		delete s2;
		for (uint j = 0; j < rest1.size(); ++j)
			got1.push_back(rest1[j]);
		for (uint j = 0; j < rest2.size(); ++j)
			got2.push_back(rest2[j]);
		TS_ASSERT(got1 == plain1);
		TS_ASSERT(got2 == plain2);
#endif
	}

	void test_capacity_evicts_least_recently_used() {
#ifdef VORBIS_SETUP_CACHE_TESTS
		Audio::VorbisSetupCache::setCapacity(2);
		delete openClip(kA1);	// miss: A
		delete openClip(kB);	// miss: A B
		delete openClip(kA2);	// hit A: B A
		delete openClip(kC);	// miss, drops B: A C
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().entries, 2u);
		delete openClip(kA3);	// hit
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().hits, 2u);
		Audio::SeekableAudioStream *b = openClip(kB);	// miss again
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().misses, 4u);
		TS_ASSERT_EQUALS(Audio::VorbisSetupCache::getStats().entries, 2u);
		Audio::VorbisSetupCache::setEnabled(false);
		const Common::Array<int16> plainB = decodeClip(kB);
		TS_ASSERT(b && readAll(b) == plainB);
		delete b;
#endif
	}
};

