#!/usr/bin/env python3
"""Bake the DOS loading screen's Korean caption into loading-caption.h.

The loading screen shows before any font is read, so its one line of
Korean is drawn from a 1bpp bitmap compiled into the executable. This
renders that line from an SVFN v2 font (the 1bpp KO2350.SVF the DOS
package ships) with the font's own advances, trims it to its ink and
writes it as a C array, MSB first, rows padded to a byte.

    python3 backends/platform/dos/mkcaption.py \
        dists/engine-data/hires_text/dos/KO2350.SVF > backends/platform/dos/loading-caption.h
"""
import struct
import sys

LICENSE = """/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */"""

CAPTION = "불러오는 중..."  # "Loading..." (bul-leo-o-neun jung)


def load_svfn(path):
    with open(path, "rb") as f:
        d = f.read()
    if d[:4] != b"SVFN":
        raise SystemExit("%s: not an SVFN font" % path)
    version, flags = struct.unpack("<HH", d[4:8])
    bpp = d[8]
    glyphs, = struct.unpack("<H", d[12:14])
    cw, ch = d[14], d[15]
    metrics_off, data_off, _ = struct.unpack("<III", d[20:32])
    if version != 2 or bpp != 1:
        raise SystemExit("%s: need a version 2, 1bpp font (got v%d, %d bpp)" % (path, version, bpp))
    cmap_off, = struct.unpack("<I", d[32:36])
    cmap = {}
    for i in range(glyphs):
        cp, idx = struct.unpack("<II", d[cmap_off + i * 8:cmap_off + i * 8 + 8])
        cmap[cp] = idx
    pitch = (cw + 7) // 8
    stride = pitch * ch

    def glyph(cp):
        idx = cmap.get(cp)
        if idx is None:
            raise SystemExit("%s has no glyph for U+%04X" % (path, cp))
        rows = []
        base = data_off + idx * stride
        for y in range(ch):
            bits = d[base + y * pitch:base + (y + 1) * pitch]
            rows.append([(bits[x // 8] >> (7 - x % 8)) & 1 for x in range(cw)])
        if flags & 1:
            adv, bearing = d[metrics_off + idx * 4], struct.unpack("<b", d[metrics_off + idx * 4 + 1:metrics_off + idx * 4 + 2])[0]
        else:
            adv, bearing = (cw if cp >= 0x1100 else cw // 2), 0
        return rows, adv, bearing

    return glyph, cw, ch


def render(glyph, cw, ch, text):
    width = 0
    placed = []
    for c in text:
        rows, adv, bearing = glyph(ord(c))
        # The stored rows start at the pen (bearing is data, see
        # SvfnGlyphSource::metrics()).
        placed.append((width, rows))
        width += adv
    canvas = [[0] * (width + cw) for _ in range(ch)]
    for x0, rows in placed:
        for y, row in enumerate(rows):
            for x, v in enumerate(row):
                if v:
                    canvas[y][x0 + x] = 1
    # Trim to the ink.
    ys = [y for y in range(ch) if any(canvas[y])]
    xs = [x for x in range(len(canvas[0])) if any(canvas[y][x] for y in range(ch))]
    return [row[xs[0]:xs[-1] + 1] for row in canvas[ys[0]:ys[-1] + 1]]


def main():
    glyph, cw, ch = load_svfn(sys.argv[1])
    bitmap = render(glyph, cw, ch, CAPTION)
    w, h = len(bitmap[0]), len(bitmap)
    pitch = (w + 7) // 8
    out = []
    for row in bitmap:
        for b in range(pitch):
            v = 0
            for i in range(8):
                x = b * 8 + i
                if x < w and row[x]:
                    v |= 0x80 >> i
            out.append(v)
    print(LICENSE)
    print()
    print("// Generated by backends/platform/dos/mkcaption.py from KO2350.SVF: do not edit.")
    print()
    print("#ifndef BACKENDS_PLATFORM_DOS_LOADING_CAPTION_H")
    print("#define BACKENDS_PLATFORM_DOS_LOADING_CAPTION_H")
    print()
    print("namespace DOS {")
    print()
    print("// U+BD88 U+B7EC U+C624 U+B294 U+0020 U+C911 ... (\"Loading...\" in Korean),")
    print("// 1bpp, MSB first, %d bytes a row." % pitch)
    print("static const int kCaptionKoWidth = %d;" % w)
    print("static const int kCaptionKoHeight = %d;" % h)
    print("static const byte kCaptionKo[%d] = {" % len(out))
    for i in range(0, len(out), 12):
        print("\t" + " ".join("0x%02x," % v for v in out[i:i + 12]))
    print("};")
    print()
    print("} // End of namespace DOS")
    print()
    print("#endif")
    # A preview on stderr, to eyeball the result.
    for row in bitmap:
        sys.stderr.write("".join("#" if v else "." for v in row) + "\n")


if __name__ == "__main__":
    main()
